stages:
    - test
    - post

include:
    - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/3fbe3d2dd7288b4c91e8b7b2fbbd98b9bdeeb92a/templates/v3/common.yml'

nvidia:test:dev:
    extends: .test
    variables:
        CI_IMAGE_TAG: 'opencl'
        CI_VERSION_TAG: 'dev'
    tags:
        - nvidia
    allow_failure: true

amd:test:dev:
    extends: .test
    variables:
        CI_IMAGE_TAG: 'rocm'
        CI_VERSION_TAG: 'dev'
    tags:
        - rocm
    allow_failure: true

nvidia:test:v1.0:
    extends: .test
    variables:
        CI_IMAGE_TAG: 'opencl'
        CI_VERSION_TAG: 'v1.0'
    tags:
        - nvidia

amd:test:v1.0:
    extends: .test
    variables:
        CI_IMAGE_TAG: 'rocm'
        CI_VERSION_TAG: 'v1.0'
    tags:
        - rocm

nvidia:test:v1.1:
    extends: .test
    variables:
        CI_IMAGE_TAG: 'opencl'
        CI_VERSION_TAG: 'v1.1'
    tags:
        - nvidia

amd:test:v1.1:
    extends: .test
    variables:
        CI_IMAGE_TAG: 'rocm'
        CI_VERSION_TAG: 'v1.1'
    tags:
        - rocm

nvidia:test:v1.2:
    extends: .test
    variables:
        CI_IMAGE_TAG: 'opencl'
        CI_VERSION_TAG: 'v1.2'
    tags:
        - nvidia

amd:test:v1.2:
    extends: .test
    variables:
        CI_IMAGE_TAG: 'rocm'
        CI_VERSION_TAG: 'v1.2'
    tags:
        - rocm

nvidia:test:v1.3:
    extends: .test
    variables:
        CI_IMAGE_TAG: 'opencl'
        CI_VERSION_TAG: 'v1.3'
    tags:
        - nvidia

amd:test:v1.3:
    extends: .test
    variables:
        CI_IMAGE_TAG: 'rocm'
        CI_VERSION_TAG: 'v1.3'
    tags:
        - rocm
